// MockDataProvider.js

const getMockData = () => {
  const company = {
    name: "Awesome Company",
    address: "Ferentexas , Bucuresti",
    phoneNumber: "+1 (555) 123-4567",
    email: "info@awesomecompany.com",
    website: "www.awesomecompany.com",
  };
  const achievements = [
    {
      image: require("../../assets/images/laLiga.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
    {
      image: require("../../assets/images/epl.png"),
      isAquiered: true,
      dateAquiered: new Date("2023-08-01"),
      importance: 1,
    },
  ];

  const users = [ 
    {
      id: 1,
      name: "Vlad the Impaler",
      email: "vlad@example.com",
      password: "password123",
      phone: "123-456-7890",
      goodPronostics: 10,
      badPronostics: 5,
      registrationDate: new Date("2023-01-01"),
      userRole: "USER",
      tournaments: [1,3,5,7]
    },
    {
      id: 2,
      name: "John Doe",
      email: "john@example.com",
      password: "password456",
      phone: "234-567-8901",
      goodPronostics: 15,
      badPronostics: 8,
      registrationDate: new Date("2023-02-01"),
      userRole: "USER",
      tournaments: [2,3,4,7]
    },
    {
      id: 3,
      name: "Aisha Ahmed",
      email: "aisha@example.com",
      password: "password789",
      phone: "+971-50-123-4567",
      goodPronostics: 12,
      badPronostics: 6,
      registrationDate: new Date("2023-03-01"),
      userRole: "USER",
      tournaments: [1,3,4,7]
    },
    {
      id: 4,
      name: "Joaquin Gonzalez",
      email: "joaquin@example.com",
      password: "password123",
      phone: "+52-33-456-7890",
      goodPronostics: 8,
      badPronostics: 10,
      registrationDate: new Date("2023-02-15"),
      userRole: "USER",
      tournaments: [2,3,5,7]
    },
    {
      id: 5,
      name: "Maria Rodriguez",
      email: "maria@example.com",
      password: "password456",
      phone: "+34-654-321-098",
      goodPronostics: 18,
      badPronostics: 2,
      registrationDate: new Date("2023-01-20"),
      userRole: "USER",
      tournaments: [1,3,6,7]
    },
    {
      id: 6,
      name: "Satoshi Nakamoto",
      email: "satoshi@example.com",
      password: "password789",
      phone: "+81-90-1234-5678",
      goodPronostics: 22,
      badPronostics: 3,
      registrationDate: new Date("2023-03-10"),
      userRole: "USER",
      tournaments: [2,3,5,7]
    },{
      id: 7,
      name: "Chen Wei",
      email: "chen@example.com",
      password: "password123",
      phone: "+86-138-1234-5678",
      goodPronostics: 9,
      badPronostics: 7,
      registrationDate: new Date("2023-03-20"),
      userRole: "USER",
      tournaments: [2,3,6,7]
    },
    {
      id: 8,
      name: "Elena Petrova",
      email: "elena@example.com",
      password: "password456",
      phone: "+7-495-123-4567",
      goodPronostics: 14,
      badPronostics: 6,
      registrationDate: new Date("2023-02-05"),
      userRole: "USER",
      tournaments: [1,3,5,6,7]
    },
    {
      id: 9,
      name: "Samantha Lee",
      email: "samantha@example.com",
      password: "password789",
      phone: "+65-9876-5432",
      goodPronostics: 11,
      badPronostics: 9,
      registrationDate: new Date("2023-03-15"),
      userRole: "USER",
      tournaments: [1,3,5,7,8]
    },
    {
      id: 10,
      name: "Gustav Bjorn",
      email: "gustav@example.com",
      password: "password123",
      phone: "+46-70-123-4567",
      goodPronostics: 7,
      badPronostics: 11,
      registrationDate: new Date("2023-02-20"),
      userRole: "USER",
      tournaments: [2,3]
    }
    
  ];

  const tournaments = [
    {
      id: 1,
      name: "Tournament 1",
      startingDate: new Date("2023-04-01"),
      endingDate: new Date("2023-04-15"),
      tournamentStatus: "OnGoing",
      championshipName: "La Liga",
      signedPlayers: 24,
      championshipId: 1,
      userId: 1,
      userPosition: "15/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'open',
      matches: [
        {
          id: 1,
          championshipId: 1,
          hostTeam: "FC Barcelona",
          guestTeam: "Real Madrid",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-01"),
          hostTeamLogoUrl: require("../../assets/images/fc_barcelona_logo.png"),
          guestTeamLogoUrl: require("../../assets/images/real_madrid_logo.png"),
          stadium: "Camp Nou",
          city: "Barcelona",
        },
        {
          id: 2,
          championshipId: 1,
          hostTeam: "Atletico Madrid",
          guestTeam: "Valencia",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-02"),
          hostTeamLogoUrl: require("../../assets/images/atletico_madrid_logo.png"),          
          guestTeamLogoUrl: require("../../assets/images/valencia_logo.png"),
          stadium: "Wanda Metropolitano",
          city: "Madrid",
        },
        {
          id: 3,
          championshipId: 1,
          hostTeam: "Sevilla",
          guestTeam: "Real Sociedad",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-03"),
          hostTeamLogoUrl: require("../../assets/images/sevilla_logo.png"),
          guestTeamLogoUrl: require("../../assets/images/real_sociedad_logo.png"),
          stadium: "Ramon Sanchez-Pizjuan",
          city: "Sevilla",
        },
        {
          id: 4,
          championshipId: 1,
          hostTeam: "Villarreal",
          guestTeam: "Athletic Club",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-04"),
          hostTeamLogoUrl: require("../../assets/images/villarreal_logo.png"),
          guestTeamLogoUrl: require("../../assets/images/athletic_club_logo.png"),
          stadium: "Estadio de la Ceramica",
          city: "Villarreal",
        },
        {
          id: 5,
          championshipId: 1,
          hostTeam: "Real Betis",
          guestTeam: "Levante",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-05"),
          hostTeamLogoUrl: require("../../assets/images/real_betis_logo.png"),
          guestTeamLogoUrl: require("../../assets/images/levante_logo.png"),
          stadium: "Benito Villamarin",
          city: "Sevilla",
        },
        {
          id: 6,
          championshipId: 1,
          hostTeam: "Celta Vigo",
          guestTeam: "Espanyol",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-06"),
          hostTeamLogoUrl: "https://example.com/celta_vigo_logo.png",
          guestTeamLogoUrl: "https://example.com/espanyol_logo.png",
          stadium: "Abanca Balaidos",
          city: "Vigo",
        },
        {
          id: 7,
          championshipId: 1,
          hostTeam: "Getafe",
          guestTeam: "Osasuna",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-07"),
          hostTeamLogoUrl: "https://example.com/getafe_logo.png",
          guestTeamLogoUrl: "https://example.com/osasuna_logo.png",
          stadium: "Coliseum Alfonso Perez",
          city: "Getafe",
        },
        {
          id: 8,
          championshipId: 1,
          hostTeam: "Granada",
          guestTeam: "Cadiz",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-08"),
          hostTeamLogoUrl: "https://example.com/granada_logo.png",
          guestTeamLogoUrl: "https://example.com/cadiz_logo.png",
          stadium: "Nuevo Los Carmenes",
          city: "Granada",
        },
        {
          id: 9,
          championshipId: 1,
          hostTeam: "Real Mallorca",
          guestTeam: "Deportivo Alaves",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-09"),
          hostTeamLogoUrl: "https://example.com/real_mallorca_logo.png",
          guestTeamLogoUrl: "https://example.com/deportivo_alaves_logo.png",
          stadium: "Visit Mallorca Estadi",
          city: "Palma",
        },
        {
          id: 10,
          championshipId: 1,
          hostTeam: "Rayo Vallecano",
          guestTeam: "Girona",
          hostTeamGoals: 3,
          guestTeamGoals: 3,
          date: new Date("2023-04-10"),
          hostTeamLogoUrl: "https://example.com/rayo_vallecano_logo.png",
          guestTeamLogoUrl: "https://example.com/girona_logo.png",
          stadium: "Estadio de Vallecas",
          city: "Madrid",
        },
      ]
    },
    {
      id: 2,
      name: "Tournament 2",
      startingDate: new Date("2023-05-01"),
      endingDate: new Date("2023-05-15"),
      tournamentStatus: "Open To Registration",
      championshipName: "Primera Division",
      signedPlayers: 24,
      championshipId: 1,
      userId: 1,
      userPosition: "30/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'closed',
      matches: matches
    },
    {
      id: 3,
      name: "Tournament 3",
      startingDate: new Date("2023-06-01"),
      endingDate: new Date("2023-06-15"),
      tournamentStatus: "Close to Registration",
      championshipName: "Premier League",
      signedPlayers: 24,
      championshipId: 2,
      userId: 1,
      userPosition: "10/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'open',
      matches: matches
    },
    {
      id: 4,
      name: "Tournament 4",
      startingDate: new Date("2023-07-01"),
      endingDate: new Date("2023-07-15"),
      tournamentStatus: "Ended",
      championshipName: "Liga 1 Bergembier",
      signedPlayers: 35,
      championshipId: 2,
      userId: 1,
      userPosition: "2/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'closed',
      matches: matches
    },
    {
      id: 5,
      name: "Tournament 5",
      startingDate: new Date("2023-08-01"),
      endingDate: new Date("2023-08-15"),
      tournamentStatus: "Upcoming",
      championshipName: "BundesLiga",
      signedPlayers: 30,
      championshipId: 3,
      userId: 1,
      userPosition: "-/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'ongoing',
      matches: matches
    },
    {
      id: 6,
      name: "Tournament 6",
      startingDate: new Date("2023-07-01"),
      endingDate: new Date("2023-07-15"),
      tournamentStatus: "Ended",
      championshipName: "Liga 1 Bergembier",
      signedPlayers: 35,
      championshipId: 2,
      userId: 1,
      userPosition: "2/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'open',
      matches: matches
    },
    {
      id: 7,
      name: "Tournament 7",
      startingDate: new Date("2023-08-01"),
      endingDate: new Date("2023-08-15"),
      tournamentStatus: "Upcoming",
      championshipName: "BundesLiga",
      signedPlayers: 30,
      championshipId: 3,
      userId: 1,
      userPosition: "-/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'closed',
      matches: matches
    },
    {
      id: 8,
      name: "Tournament 8",
      startingDate: new Date("2023-08-01"),
      endingDate: new Date("2023-08-15"),
      tournamentStatus: "Upcoming",
      championshipName: "BundesLiga",
      signedPlayers: 30,
      championshipId: 3,
      userId: 1,
      userPosition: "-/30",
      totalPositions: 30,
      usersSignedInTournament: 30,
      status: 'closed',
      matches: matches
    },
    {
      id: 9,
      name: "Tournament 9",
      startingDate: new Date("2023-08-01"),
      endingDate: new Date("2023-08-15"),
      tournamentStatus: "Upcoming",
      championshipName: "BundesLiga",
      signedPlayers: 30,
      championshipId: 3,
      userId: 1,
      userPosition: "-/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'closed',
      matches: matches
    },
    {
      id: 10,
      name: "Tournament 10",
      startingDate: new Date("2023-08-01"),
      endingDate: new Date("2023-08-15"),
      tournamentStatus: "Upcoming",
      championshipName: "BundesLiga",
      signedPlayers: 30,
      championshipId: 3,
      userId: 1,
      userPosition: "-/30",
      totalPositions: 30,
      usersSignedInTournament: 15,
      status: 'closed',
      matches: matches
    },
  ];

  const championships = [
    {
      name: "English Premier League",
      id: 1,
      teams: 20,
      country: "England",
      image: require("../../assets/images/epl.png"),
      championshipType: "League",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "La Liga",
      id: 2,
      teams: 20,
      country: "Spain",
      image: require("../../assets/images/laLiga.png"),
      championshipType: "League",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "Bundesliga",
      id: 3,
      teams: 18,
      country: "Germany",
      image: require("../../assets/images/bundesliga.png"),
      championshipType: "League",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "Serie A",
      id: 4,
      teams: 20,
      country: "Italy",
      image: require("../../assets/images/seriaA.png"),
      championshipType: "League",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "Ligue 1",
      id: 5,
      teams: 20,
      country: "France",
      image: require("../../assets/images/ligue1.png"),
      championshipType: "League",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "UEFA Champions League",
      id: 6,
      teams: 32,
      country: "Europe",
      image: require("../../assets/images/championsLeague.png"),
      championshipType: "Cup",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "UEFA Europa League",
      id: 7,
      teams: 48,
      country: "Europe",
      image: require("../../assets/images/europaLeague.png"),
      championshipType: "Cup",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
    {
      name: "FIFA World Cup",
      id: 8,
      teams: 32,
      country: "International",
      image: require("../../assets/images/worldCup.png"),
      championshipType: "Cup",
      startDate: new Date("2023-08-01"),
      endDate: new Date("2024-05-20"),
    },
  ];

  const matches = [
    {
      id: 1,
      championshipId: 1,
      hostTeam: "FC Barcelona",
      guestTeam: "Real Madrid",
      date: new Date("2023-04-01"),
      hostTeamLogoUrl: "https://example.com/fc_barcelona_logo.png",
      guestTeamLogoUrl: "https://example.com/real_madrid_logo.png",
      stadium: "Camp Nou",
      city: "Barcelona",
    },
    {
      id: 2,
      championshipId: 1,
      hostTeam: "Atletico Madrid",
      guestTeam: "Valencia",
      date: new Date("2023-04-02"),
      hostTeamLogoUrl: "https://example.com/atletico_madrid_logo.png",
      guestTeamLogoUrl: "https://example.com/valencia_logo.png",
      stadium: "Wanda Metropolitano",
      city: "Madrid",
    },
    {
      id: 3,
      championshipId: 1,
      hostTeam: "Sevilla",
      guestTeam: "Real Sociedad",
      date: new Date("2023-04-03"),
      hostTeamLogoUrl: "https://example.com/sevilla_logo.png",
      guestTeamLogoUrl: "https://example.com/real_sociedad_logo.png",
      stadium: "Ramon Sanchez-Pizjuan",
      city: "Sevilla",
    },
    {
      id: 4,
      championshipId: 1,
      hostTeam: "Villarreal",
      guestTeam: "Athletic Club",
      date: new Date("2023-04-04"),
      hostTeamLogoUrl: "https://example.com/villarreal_logo.png",
      guestTeamLogoUrl: "https://example.com/athletic_club_logo.png",
      stadium: "Estadio de la Ceramica",
      city: "Villarreal",
    },
    {
      id: 5,
      championshipId: 1,
      hostTeam: "Real Betis",
      guestTeam: "Levante",
      date: new Date("2023-04-05"),
      hostTeamLogoUrl: "https://example.com/real_betis_logo.png",
      guestTeamLogoUrl: "https://example.com/levante_logo.png",
      stadium: "Benito Villamarin",
      city: "Sevilla",
    },
    {
      id: 6,
      championshipId: 1,
      hostTeam: "Celta Vigo",
      guestTeam: "Espanyol",
      date: new Date("2023-04-06"),
      hostTeamLogoUrl: "https://example.com/celta_vigo_logo.png",
      guestTeamLogoUrl: "https://example.com/espanyol_logo.png",
      stadium: "Abanca Balaidos",
      city: "Vigo",
    },
    {
      id: 7,
      championshipId: 1,
      hostTeam: "Getafe",
      guestTeam: "Osasuna",
      date: new Date("2023-04-07"),
      hostTeamLogoUrl: "https://example.com/getafe_logo.png",
      guestTeamLogoUrl: "https://example.com/osasuna_logo.png",
      stadium: "Coliseum Alfonso Perez",
      city: "Getafe",
    },
    {
      id: 8,
      championshipId: 1,
      hostTeam: "Granada",
      guestTeam: "Cadiz",
      date: new Date("2023-04-08"),
      hostTeamLogoUrl: "https://example.com/granada_logo.png",
      guestTeamLogoUrl: "https://example.com/cadiz_logo.png",
      stadium: "Nuevo Los Carmenes",
      city: "Granada",
    },
    {
      id: 9,
      championshipId: 1,
      hostTeam: "Real Mallorca",
      guestTeam: "Deportivo Alaves",
      date: new Date("2023-04-09"),
      hostTeamLogoUrl: "https://example.com/real_mallorca_logo.png",
      guestTeamLogoUrl: "https://example.com/deportivo_alaves_logo.png",
      stadium: "Visit Mallorca Estadi",
      city: "Palma",
    },
    {
      id: 10,
      championshipId: 1,
      hostTeam: "Rayo Vallecano",
      guestTeam: "Girona",
      date: new Date("2023-04-10"),
      hostTeamLogoUrl: "https://example.com/rayo_vallecano_logo.png",
      guestTeamLogoUrl: "https://example.com/girona_logo.png",
      stadium: "Estadio de Vallecas",
      city: "Madrid",
    },
  ];

  const pronosticData = [
    {
      id: 1,
      matchId: 1,
      userId: 1,
      hostTeamGoalsPronostic: 2,
      guestTeamGoalsPronostic: 1,
      goalsDifferencePronostic: 1
    },
    {
      id: 2,
      matchId: 1,
      userId: 2,
      hostTeamGoalsPronostic: 3,
      guestTeamGoalsPronostic: 2,
      goalsDifferencePronostic: 1
    },
    {
      id: 3,
      matchId: 1,
      userId: 3,
      hostTeamGoalsPronostic: 1,
      guestTeamGoalsPronostic: 2,
      goalsDifferencePronostic: -1
    },
    {
      id: 4,
      matchId: 2,
      userId: 1,
      hostTeamGoalsPronostic: 2,
      guestTeamGoalsPronostic: 0,
      goalsDifferencePronostic: 2
    },
    {
      id: 5,
      matchId: 2,
      userId: 2,
      hostTeamGoalsPronostic: 1,
      guestTeamGoalsPronostic: 1,
      goalsDifferencePronostic: 0
    },
    {
      id: 6,
      matchId: 2,
      userId: 3,
      hostTeamGoalsPronostic: 3,
      guestTeamGoalsPronostic: 1,
      goalsDifferencePronostic: 2
    },
    {
      id: 7,
      matchId: 3,
      userId: 1,
      hostTeamGoalsPronostic: 2,
      guestTeamGoalsPronostic: 1,
      goalsDifferencePronostic: 1
    },
  ];

  const pronostics = [
    {
      id: 1,
      userId: 1,
      matchId: 1,
      homeTeamScore: 2,
      awayTeamScore: 1,
      createdAt: new Date("2023-03-30"),
      updatedAt: new Date("2023-03-30"),
    },
    {
      id: 2,
      userId: 2,
      matchId: 1,
      homeTeamScore: 1,
      awayTeamScore: 1,
      createdAt: new Date("2023-03-29"),
      updatedAt: new Date("2023-03-29"),
    },
  ];

  return {
    users,
    tournaments,
    championships,
    matches,
    pronostics,
    achievements,
    company,
    pronosticData,
  };
};

export default getMockData;